name: benchmark
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  routingkit: ^0.2.1
  shelf_router: ^1.1.4
  spanner: ^1.0.1+5
  alfred: any
  shelf_openrouter:
    path: ..

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
