name: shelf_openrouter
description: Fast and extensible routing for the shelf ecosystem with a shelf_router compatible api.
version: 0.0.1
repository: https://github.com/helightdev/shelf_openrouter
issue_tracker: https://github.com/helightdev/catwalk/issues
topics: ["shelf", "routing", "http"]

environment:
  sdk: ^3.4.3

dependencies:
  shelf: ^1.4.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
